# tasks file for kibana-role
  - name: Upload tar.gz Kibana from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      mode: 0644
      timeout: 60
      force: true
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana
    file:
      state: directory
      path: "{{ kibana_home }}"
      mode: 0755
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [ --strip-components=1 ]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
      - kibana
  - name: Configure Kibana to be available on any interface
    become: yes
    lineinfile:
      path: "{{ kibana_home }}/config/kibana.yml"
      line: 'server.host: "0.0.0.0"'
    tags: kibana
  - name: Set environment Kibana
    become: true
    template:
      src: templates/kibana.sh.j2
      dest: /etc/profile.d/kibana.sh
      mode: 0755
    tags: kibana
